OS=Windows 11
Browser=Firefox
Automation Tool=Playwright
Language=TypeScript
BDD=Cucumber
Node=24.18.1
Java=JDK 21
Application=OrangeHRM
Environment=QA
URL=http://127.0.0.1/orangehrm-2.5.0.2/login.php 